services:
  notes-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "default"
    expose:
      - "8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  sonar-exporter:
    image: python:3.12-alpine
    container_name: sonar-exporter
    ports:
      - "9100:9100"
    environment:
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
      SONAR_TOKEN: ${SONAR_TOKEN}
    volumes:
      - ./scripts/exporter.py:/app/exporter.py
    entrypoint: ["python3", "/app/exporter.py"]
